import{a as b,S,i as d}from"./assets/vendor-550cebad.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();async function m(e,r){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"43027041-c13525989a1527b0b019a35b5",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15})}`;return(await b.get(s)).data}function w(e){const{largeImageURL:r,webformatURL:n,tags:s,likes:t,views:a,comments:i,downloads:L}=e;return`<li class="image-items">
        <a class="image-link" href="${r}">
          <img
            src="${n}"
            alt="${s}"
            class="photo-image"
          />
        </a>
        <div class="image-info">
          <p><span class="accent">Likes:</span> ${t}</p>
          <p><span class="accent">Views:</span> ${a}</p>
          <p><span class="accent">Comments:</span> ${i}</p>
          <p><span class="accent">Downloads:</span> ${L}</p>
        </div>
      </li>`}function v(e){return e.map(w).join("")}function h(e){const r=v(e);new S(".image-link",{captionsData:"alt",captionDelay:250}).refresh(),o.gallery.insertAdjacentHTML("beforeend",r)}const o={searchForm:document.querySelector(".search-form"),inputSearch:document.querySelector(".input-search"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-load-more"),loader:document.querySelector(".loader")};function q(){o.btnLoadMore.classList.remove("hidden")}function M(){o.btnLoadMore.classList.add("hidden")}let c,l,p=0;const P=15;function u(e){d.error({title:"Error",message:e,position:"topRight"})}function E(e){d.error({title:"Error",message:e,position:"bottomRight"})}function g(){l>=p?(M(),E("We're sorry, but you've reached the end of search results.")):q()}function f(){o.loader.classList.remove("hidden")}function y(e){o.loader.classList.add("hidden")}function $(){const e=o.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})}o.searchForm.addEventListener("submit",x);async function x(e){if(e.preventDefault(),c=e.target.elements.name.value.trim(),l=1,o.gallery.innerHTML="",!c){u("Sorry, there are no images matching your search query. Please try again!");return}f();try{const r=await m(c,l);p=Math.ceil(r.totalHits/P),h(r.hits)}catch{u("Sorry, there are no images matching your search query. Please try again!")}y(),g(),e.target.reset()}o.btnLoadMore.addEventListener("click",O);async function O(){f();try{const e=await m(c,l+=1);h(e.hits)}catch{u("Sorry, there are no images matching your search query. Please try again!")}$(),y(),g()}
//# sourceMappingURL=commonHelpers.js.map
