import{a as S,S as w,i as d}from"./assets/vendor-550cebad.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=i(t);fetch(t.href,a)}})();async function m(e,r){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"43027041-c13525989a1527b0b019a35b5",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15})}`;return(await S.get(s)).data}const o={searchForm:document.querySelector(".search-form"),inputSearch:document.querySelector(".input-search"),gallery:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".btn-load-more"),loader:document.querySelector(".loader")},v=new w(".image-link",{captionsData:"alt",captionDelay:250});function q(e){const{largeImageURL:r,webformatURL:i,tags:s,likes:t,views:a,comments:n,downloads:b}=e;return`<li class="image-items">
        <a class="image-link" href="${r}">
          <img
            src="${i}"
            alt="${s}"
            class="photo-image"
          />
        </a>
        <div class="image-info">
          <p><span class="accent">Likes:</span> ${t}</p>
          <p><span class="accent">Views:</span> ${a}</p>
          <p><span class="accent">Comments:</span> ${n}</p>
          <p><span class="accent">Downloads:</span> ${b}</p>
        </div>
      </li>`}function M(e){return e.map(q).join("")}function h(e){const r=M(e);o.gallery.insertAdjacentHTML("beforeend",r),v.refresh()}function P(){o.btnLoadMore.classList.remove("hidden")}function p(){o.btnLoadMore.classList.add("hidden")}let c,l,f=0;const E=15;function u(e){d.error({title:"Error",message:e,position:"topRight"})}function $(e){d.error({title:"Error",message:e,position:"bottomRight"})}function g(){l>=f?(p(),$("We're sorry, but you've reached the end of search results.")):P()}function y(){o.loader.classList.remove("hidden")}function L(e){o.loader.classList.add("hidden")}function O(){const e=o.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:e*2,behavior:"smooth"})}o.searchForm.addEventListener("submit",R);async function R(e){if(e.preventDefault(),c=e.target.elements.name.value.trim(),l=1,o.gallery.innerHTML="",!c){u("Sorry, there are no images matching your search query. Please try again!"),p();return}y();try{const r=await m(c,l);f=Math.ceil(r.totalHits/E),h(r.hits)}catch{u("Sorry, there are no images matching your search query. Please try again!")}L(),g(),e.target.reset()}o.btnLoadMore.addEventListener("click",x);async function x(){y();try{const e=await m(c,l+=1);h(e.hits)}catch{u("Sorry, there are no images matching your search query. Please try again!")}O(),g(),L()}
//# sourceMappingURL=commonHelpers.js.map
